/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.PedidoClienteController;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;


/**
 *
 * @author ester
 */
public class TelaMeusPedidos extends javax.swing.JFrame {

    private PedidoClienteController pedidoController;
    /**
     * Creates new form TelaMeusPedidos
     */
    public TelaMeusPedidos() {
        initComponents();
         this.pedidoController = new PedidoClienteController();
        carregarMeusPedidos();
    }
      // MÉTODO PARA CARREGAR OS PEDIDOS DO CLIENTE
    private void carregarMeusPedidos() {
        DefaultTableModel modelo = (DefaultTableModel) tblPedido.getModel();
        modelo.setRowCount(0); // Limpa a tabela
        
        // Verifica se o usuário está logado
        if (!pedidoController.usuarioEstaLogado()) {
            JOptionPane.showMessageDialog(this, "Você precisa estar logado!");
            this.dispose();
            return;
        }
        
        // Busca os pedidos do cliente
        List<Object[]> dados = pedidoController.buscarMeusPedidos();
        
        // Adiciona os dados na tabela
        if (dados != null && !dados.isEmpty()) {
            for (Object[] linha : dados) {
                modelo.addRow(linha);
            }
        } else {
            modelo.addRow(new Object[]{"-", "Nenhum pedido encontrado", "-", "-"});
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();
        txt_estoque = new javax.swing.JLabel();
        bntCancelar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Status", "Preço", "Pagamento"
            }
        ));
        jScrollPane1.setViewportView(tblPedido);

        txt_estoque.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_estoque.setForeground(new java.awt.Color(255, 204, 0));
        txt_estoque.setText("Meu Pedido");

        bntCancelar.setBackground(new java.awt.Color(255, 204, 0));
        bntCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntCancelar.setText("Cancelar Pedido");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(255, 204, 0));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(txt_estoque))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(btnVoltar)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(txt_estoque)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(bntCancelar)
                .addGap(35, 35, 35)
                .addComponent(btnVoltar)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        // TODO add your handling code here:
 int linhaSelecionada = tblPedido.getSelectedRow();
    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um pedido para cancelar!");
        return;
    }

    int idPedido = (int) tblPedido.getValueAt(linhaSelecionada, 0);
    String statusAtual = (String) tblPedido.getValueAt(linhaSelecionada, 1);
    
    // Verifica se o pedido pode ser cancelado
    if ("Entregue".equals(statusAtual) || "Cancelado".equals(statusAtual) || "Pronto".equals(statusAtual)) {
        JOptionPane.showMessageDialog(this, 
            "Não é possível cancelar um pedido com status: " + statusAtual + "\n" +
            "Apenas pedidos 'Pendente' ou 'Em Preparação' podem ser cancelados.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, 
        "Cancelar pedido #" + idPedido + "?\n\n" +
        "Esta ação não pode ser desfeita.\n" +
        "O valor será estornado conforme a política de cancelamento.",
        "Confirmar Cancelamento",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE);
        
    if (confirm == JOptionPane.YES_OPTION) {
        boolean sucesso = pedidoController.cancelarMeuPedido(idPedido);
        if (sucesso) {
            JOptionPane.showMessageDialog(this, 
                "Pedido #" + idPedido + " cancelado com sucesso!\n" +
                "O estorno será processado em até 2 dias úteis.",
                "Cancelamento Concluído", 
                JOptionPane.INFORMATION_MESSAGE);
            carregarMeusPedidos(); // Recarrega a tabela
        } else {
            JOptionPane.showMessageDialog(this, 
                "Erro ao cancelar pedido!\n" +
                "Tente novamente ou entre em contato com o suporte.",
                "Erro no Cancelamento", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        new PainelAluno().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMeusPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMeusPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMeusPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMeusPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMeusPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPedido;
    private javax.swing.JLabel txt_estoque;
    // End of variables declaration//GEN-END:variables
}
