/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.PedidoController;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author ester
 */
public class TelaPedidoAdm extends javax.swing.JFrame {

    private PedidoController pedidoController;

    /**
     * Creates new form TelaPedidoAdm
     */
    public TelaPedidoAdm() {
        initComponents();    
        this.pedidoController = new PedidoController();
        carregarPedidos(); // Carrega os pedidos ao abrir a tela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();
        txt_estoque = new javax.swing.JLabel();
        txtfield_pesquisar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnPedidoConcluido = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Status", "Preço", "Pagamento"
            }
        ));
        jScrollPane1.setViewportView(tblPedido);

        txt_estoque.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_estoque.setForeground(new java.awt.Color(255, 204, 0));
        txt_estoque.setText("Pedido");

        btnBuscar.setBackground(new java.awt.Color(255, 204, 0));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnPedidoConcluido.setBackground(new java.awt.Color(255, 204, 0));
        btnPedidoConcluido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPedidoConcluido.setText("Pedido Concluído");
        btnPedidoConcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoConcluidoActionPerformed(evt);
            }
        });

        bntCancelar.setBackground(new java.awt.Color(255, 204, 0));
        bntCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntCancelar.setText("Cancelar Pedido");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(255, 204, 0));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVoltar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtfield_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(txt_estoque))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPedidoConcluido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(txt_estoque)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfield_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnPedidoConcluido)
                        .addGap(43, 43, 43)
                        .addComponent(bntCancelar)))
                .addGap(37, 37, 37)
                .addComponent(btnVoltar)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarPedidos() {
        DefaultTableModel modelo = (DefaultTableModel) tblPedido.getModel();
        modelo.setRowCount(0); // Limpa a tabela
        
        // Busca os dados do controller
        List<Object[]> dados = pedidoController.buscarDadosParaTabela();
        
        // Adiciona os dados na tabela
        if (dados != null && !dados.isEmpty()) {
            for (Object[] linha : dados) {
                modelo.addRow(linha);
            }
        } else {
            // Se não houver dados, mostra mensagem
            modelo.addRow(new Object[]{"-", "Nenhum pedido encontrado", "-", "-"});
        }
    }
    private void btnPedidoConcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoConcluidoActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblPedido.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um pedido na tabela!");
            return;
        }
        
        int idPedido = (int) tblPedido.getValueAt(linhaSelecionada, 0);
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Marcar pedido #" + idPedido + " como CONCLUÍDO?",
            "Confirmar Conclusão",
            JOptionPane.YES_NO_OPTION);
            
        if (confirm == JOptionPane.YES_OPTION) {
            boolean sucesso = pedidoController.marcarComoConcluido(idPedido);
            if (sucesso) {
                JOptionPane.showMessageDialog(this, "Pedido marcado como concluído!");
                carregarPedidos(); // Recarrega a tabela
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao marcar pedido como concluído!");
            }
        }
       
    }//GEN-LAST:event_btnPedidoConcluidoActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        // TODO add your handling code here:
       int linhaSelecionada = tblPedido.getSelectedRow();
    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um pedido para cancelar!");
        return;
    }

    int idPedido = (int) tblPedido.getValueAt(linhaSelecionada, 0);
    String statusAtual = (String) tblPedido.getValueAt(linhaSelecionada, 1);
    
    // Verifica se o pedido pode ser cancelado
    if ("Entregue".equals(statusAtual) || "Cancelado".equals(statusAtual) || "Pronto".equals(statusAtual)) {
        JOptionPane.showMessageDialog(this, 
            "Não é possível cancelar um pedido com status: " + statusAtual + "\n" +
            "Apenas pedidos 'Pendente' ou 'Em Preparação' podem ser cancelados.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, 
        "Cancelar pedido #" + idPedido + "?\n\n" +
        "Esta ação não pode ser desfeita.\n" +
        "O valor será estornado conforme a política de cancelamento.",
        "Confirmar Cancelamento",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE);
        
    if (confirm == JOptionPane.YES_OPTION) {
        boolean sucesso = pedidoController.cancelarPedido(idPedido);
        if (sucesso) {
            JOptionPane.showMessageDialog(this, 
                "Pedido #" + idPedido + " cancelado com sucesso!\n" +
                "O estorno será processado em até 2 dias úteis.",
                "Cancelamento Concluído", 
                JOptionPane.INFORMATION_MESSAGE);
            carregarPedidos(); // Recarrega a tabela
        } else {
            JOptionPane.showMessageDialog(this, 
                "Erro ao cancelar pedido!\n" +
                "Tente novamente ou entre em contato com o suporte.",
                "Erro no Cancelamento", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
                  
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        new PainelAdmin().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
       // Para simplificar, vamos recarregar todos os pedidos
        carregarPedidos();
        JOptionPane.showMessageDialog(this, "Buscar funcionalidade em desenvolvimento!");
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPedidoAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPedidoAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPedidoAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPedidoAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPedidoAdm().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnPedidoConcluido;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPedido;
    private javax.swing.JLabel txt_estoque;
    private javax.swing.JTextField txtfield_pesquisar;
    // End of variables declaration//GEN-END:variables
}
