/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.PainelAdminController;

import javax.swing.JButton;
/**
 *
 * 
 */
public class PainelAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PainelAdmin
     */
    public PainelAdmin() {
        initComponents();
        new Controller.PainelAdminController(this, btnCadastrarCardapio);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbldescricao = new javax.swing.JLabel();
        btnCadastrarCardapio = new javax.swing.JButton();
        btnNaTelainicialADMEstoque = new javax.swing.JButton();
        btnPedidioAdm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lbldescricao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbldescricao.setForeground(new java.awt.Color(255, 255, 0));
        lbldescricao.setText("Bem-vindo!!");

        btnCadastrarCardapio.setBackground(new java.awt.Color(0, 0, 0));
        btnCadastrarCardapio.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnCadastrarCardapio.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarCardapio.setText("CADASTRAR  CARDAPIO");
        btnCadastrarCardapio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 0)));
        btnCadastrarCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCardapioActionPerformed(evt);
            }
        });

        btnNaTelainicialADMEstoque.setBackground(new java.awt.Color(0, 0, 0));
        btnNaTelainicialADMEstoque.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnNaTelainicialADMEstoque.setForeground(new java.awt.Color(255, 255, 255));
        btnNaTelainicialADMEstoque.setText("ESTOQUE");
        btnNaTelainicialADMEstoque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 0)));
        btnNaTelainicialADMEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaTelainicialADMEstoqueActionPerformed(evt);
            }
        });

        btnPedidioAdm.setBackground(new java.awt.Color(0, 0, 0));
        btnPedidioAdm.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnPedidioAdm.setForeground(new java.awt.Color(255, 255, 255));
        btnPedidioAdm.setText("PEDIDO");
        btnPedidioAdm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 0)));
        btnPedidioAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidioAdmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNaTelainicialADMEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addComponent(lbldescricao))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPedidioAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCadastrarCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbldescricao)
                .addGap(82, 82, 82)
                .addComponent(btnNaTelainicialADMEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnPedidioAdm)
                .addGap(37, 37, 37)
                .addComponent(btnCadastrarCardapio)
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCardapioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarCardapioActionPerformed

    private void btnNaTelainicialADMEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaTelainicialADMEstoqueActionPerformed
        // TODO add your handling code here:
        TelaEstoque tela = new TelaEstoque();
        tela.setVisible(true);
        

    }//GEN-LAST:event_btnNaTelainicialADMEstoqueActionPerformed

    private void btnPedidioAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidioAdmActionPerformed
        // TODO add your handling code here:
        
        new View.TelaPedidoAdm().setVisible(true);
        this.dispose();
   
    }//GEN-LAST:event_btnPedidioAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelAdmin().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCardapio;
    private javax.swing.JButton btnNaTelainicialADMEstoque;
    private javax.swing.JButton btnPedidioAdm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbldescricao;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCadastrarCardapio() {
        return btnCadastrarCardapio;
    }
}
